<?php 
drupal_add_css(drupal_get_path('module', 'jwstream') . '/css/jwstream.css');
drupal_add_js(drupal_get_path('module', 'jwstream') . '/mediaplayer-5.9/jwplayer.js');
module_load_include('inc', 'jwstream');

function jwstream_field_info() {
  return array(
    'jwstream_field_info' => array(
      'label' => t('JWStream'),
      'description' => t('This field stores the boolean value in the database'),
      'default_widget' => 'jwstream_field_widget',
      'default_formatter' => 'jwstream_field_formatter',
    ),
  );
}

function jwstream_field_is_empty($item, $field) {
  return empty($item['stream']);
}

function jwstream_field_formatter_info() {
  return array(
    'jwstream_field_formatter' => array(
      'label' => t('Default'),
      'field types' => array('jwstream_field_info'),
    ),
  );
}

function jwstream_field_widget_info() {
  return array(
    'jwstream_field_widget' => array(
       'label' => t('JWStream Widget'),
       'field types' => array('jwstream_field_info'),
    ),
  );
}

function jwstream_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['stream']) ? $items[$delta]['stream'] : '';
  
	$widget = $element;
	$widget['#delta'] = $delta;
	
  switch ($instance['widget']['type']) {
		case 'jwstream_field_widget':
			$widget += array(
				'#type' => 'checkbox',
				'#default_value' => !module_exists('file') ? 0 : $value,
        '#description' => t('Selecting this option enables streaming.'),
			);
			break;
	}
	
	$element['stream'] = $widget;
	return $element;
}

function jwstream_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  switch ($display['type']) {
    case 'jwstream_field_formatter':
      $node_path = explode('/', current_path());
      $player = drupal_get_path('module', 'jwstream') . '/mediaplayer-5.9/player.swf';
      $html = '<div id="mediaplayer"></div>';
      $file_name = getMediaFilePath($node_path[1]);
      $file_path = variable_get(file_public_path);
      echo $html;
      drupal_add_js('misc/jquery.js');
      drupal_add_js('jwplayer("mediaplayer").setup(
        {
          "flashplayer": "' . $player . '",
          "id": "playerID",
          "width": "480",
          "height": "270",
          "file": "sites/default/files/' . $file_name .'",
          "provider": "http",
          "http.startparam": "starttime"
         });', 'inline');
       break;
  }
}

function jwstream_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  if (!module_exists('file')) {
    $errors[$field['field_name']][$langcode][$delta][] = array(
      'error' => 'File module not enabled.',
      'message' => t('<i>Enable the File module.</i>'),
    );
  }
}

function jwstream_menu() {
  $items['admin/jwstream'] = array(
    'title' => 'JWStream',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jwstream_settings_page'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function jwstream_settings_page() {
  $form['settings']['streaming_server_protocol'] = array(
    '#type' => 'select',
    '#title' => t('Protocol: '),
    '#options' => array(0 => '---Select One---', 2 => 'http', 3 => 'https'),
    '#default_value' => variable_get('protocol', array('2' => 'http')),
    '#description' => t('<i>Please select a protocol for your CDN</i>'),
    '#required' => TRUE,
  );

  $form['settings']['streaming_server_url'] = array(
    '#type' => 'textfield',
    '#title' => t('CDN Url: '),
    '#default_value' => variable_get('cdn_url', 'http://localhost'),
    '#description' => t('<i>Please declare the CDN url</i>'),
    '#size' => 50,
    '#required' => TRUE,
  );

  $form['settings']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#validate' => array('jwstream_validate'),
    '#submit' => array('jwstream_settings_submit'),
  );
  return $form;
}

function jwstream_validate($form, &$form_state) {
  if ($form_state['values']['streaming_server_protocol'] == 0) {
    form_set_error('streaming_server_protocol', t('<i>Please select a valid Protocol.</i>'));
  }

  if(valid_url($form_state['values']['streaming_server_url'], TRUE) == FALSE) {
    form_set_error('streaming_server_url', t('<i>Please select a valid URL.</i>'));
  }
} 

function jwstream_settings_submit($form, $form_state) {
  variable_set('protocol', $form_state['values']['streaming_server_protocol']);
  variable_set('cdn_url', $form_state['values']['streaming_server_url']);
}
